---
title: "Open Data Day Hackathon"
---

Can you imagine ways to improve public transport in your city? Do you know or wish to learn how to wrangle, analyse, visualize or communicate with data? Join our upcoming hackathon in Zürich, meet people from the open data community - and let's make an impact together on all the ways we get around!

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
library("ggmap")
zrh <- get_map(location = "Zurich", zoom = 12, source="stamen", maptype="toner")
ggmap(zrh)
```

<div class="boxed">
Toghether with 
[Open Data Zurich](https://www.stadt-zuerich.ch/opendata),
[VBZ](https://www.stadt-zuerich.ch/vbz/en/index.html) and
the [Master Program in Biostatistics UZH](http://www.biostat.uzh.ch/)
the [Zürich R Meetup Group](https://www.meetup.com/Zurich-R-User-Group/messages/boards/) 
will hold a hackathon on occasion of the


**[Open Data Day](http://opendataday.org/) - Saturday, March 4, 2017**.    
09:00 - 18:00, UZH main building (Rämistrasse 71, rooms KO2-F-150 and KO2-F-152)

The event will include time for hacking but we will also invite some speakers
for talks. Food and drinks will be provided. All you have to bring is your
laptop.
</div> 

You do not need to be a data science superhero yet. It is completely fine if you 
have basic skills in **one** of the following:

- Combining and cleaning data sets
- Creating graphs and visualisations
- Creating statistics or models
- Creating slides, documents, websites or anything else to communicate the results

For analyses you can use *any open data* you like. VBZ provides *transport delay* 
and *passenger count* data via the [Zurich Open Data Portal](https://data.stadt-zuerich.ch/dataset?sort=score+desc%2C+metadata_modified+desc&tags=vbz). The goal is it to
use open source software (such as [R](https://www.r-project.org/)) to 
get interesting new insights and share them with the world. 

<input type="button" onclick="location.href='https://docs.google.com/forms/d/e/1FAIpQLScX3UngiEGdmymcrbj8Wvpcw0vtDynJyekyWLYCP5qodzAPqg/viewform';" value="Sign up now!" />    
There is limited space. The first 60 people signed up get the spot.   
Closing date: 26.02.2017


----

**Preparation for the event**

- We are starting to collect ideas on what we could do. Add your ideas
[here](https://github.com/OpenDataDayZurich2016/ideas).

- We will do a data preparation evening on the February 21. 
[RSVP here](https://www.meetup.com/Zurich-R-User-Group/events/237068776/).


----

Partners: 
[Open Data Zurich](https://data.stadt-zuerich.ch/),
[VBZ](https://www.stadt-zuerich.ch/vbz/en/index.html),
[Master Program in Biostatistics UZH](http://www.biostat.uzh.ch/),
[Opendata.ch](http://opendata.ch)

Hashtag: \#ODDZurich, [VBZ Blogpost about the event](https://vbzonline.ch/2017/01/26/es-ware-schade-wenn-diese-daten-nicht-ausgewertet-wurden/)
