---
title: "Slides"
output:
  html_document:
    df_print: paged
---

Here you can find slides from past meetups.

### November 13

- [Predicting the departing runway of a flight based on a classification tree model](slides/20191113_Perucco.pdf) (Benjamin Perucco, Zurich Airport)
- NOTAM message classifier (Joao Banha, Swiss International Air Lines)

### October 14, 2019

- [quanteda - Quantitative Analysis of Textual Data](slides/20191014_quanteda.pdf) (Stefan Müller, UZH)
- [useR!2019 Toulouse : ZRH-PARIS-BORDEAUX-TOULOUSE](https://zhr-meetup-201910.netlify.com/#1) (Matthias Bannert, KOF/ETHZ)

### September 16, 2019

- Relational data models with the dm package: [R script](https://github.com/krlmlr/dm/blob/master/demo/zurich.R), [package website](https://krlmlr.github.io/dm/) (Kirill Müller, cynkra)
- [Tracking Real Estate Project Web Sites with R](slides/20190916_Pres_Datahouse_Crawling.pdf) (Thomas Maier, Datahouse AG)

### June 18, 2019

- [Use case of reinforcement-learning examplified by Super Mario AI](slides/20190618_reinforcelearn.pdf) (Sebastian Heinz \& Oliver Guggenbühl, STATWORX)
- [Analytical Data Management with R](slides/20190618_duckdb.pdf) (Hannes Mühleisen, CWI, University of Amsterdam (UvA))

### May 22, 2019

- [Docker for R users](https://lyndametref.github.io/docker4r-presentation/docs/) (Lynda Metref, Helbling Technik AG)
- [Toward production-ready user interfaces with the R Shiny framework](https://rinterface.com/shiny/talks/index.html) (David Granjon, UZH)

### April 03, 2019

- Medical underwriting triage: An end-to-end machine learning case study (Alexander Noll, PartnerRe)
- [Introducing chartbookR](slides/20190403_Reber_chartbookR.pdf) (Kilian Reber, SUVA)

### February 19, 2019

- [On weapons and dialects: The initial hypothesis and the final story](slides/20190219_talkMJK.pdf) (Marie-José Kolly, NZZ)
- [Data driven journalism at Tamedia](https://docs.google.com/presentation/d/1wWc-yjw33mIA8SrOQd16OoIID54L0wU5mNV4410RxKk) (Patrick Meier, Tamedia)

### December 5, 2018

- [What I find important when R Programming - and Recent Cool Features in R](https://stat.ethz.ch/~maechler/U/R/Zurich_R-2018_ProgR-ALTREP.html#1) (Dr. Martin Mächler, ETH Zurich)

### October 25, 2018

- [A Comparison of Covariate-based Prediction Methods for FIFA World Cups](slides/20181025_useR_predicting_FIFA_groll.pdf) (Andreas Groll, TU Dortmund)
- [Predicting biathlon shooting performance using machine learning](slides/20181025_useR_predicting_biathlon_maier.pdf) (Thomas Maier, Swiss Federal Institute of Sport Magglingen/datahouse)

### September 3, 2018

- [blogdown: Creating Websites with R Markdown](slides/20180903_blogdown_rmeetup_tlorusso.pdf) (Thomas Lo Russo, Statistical Office, Canton of Zurich)
- [DBI: Recent developments in R's database interface](https://krlmlr.github.io/dbi-slides/2018-09-zurich-meetup/) (Kirill Müller, cynkra GmbH)

### May 16, 2018

- [Micro location rating in real estate](slides/20180516_Pres_Schweizer.pdf) (Jacqueline Schweizer, Wüest Partner)
- [Speeding R up on your computer by parallelized computations - a geostatistical case study](slides/20180516_Pres_Papritz.pdf) (Andreas Papritz, Department of Environmental Systems Science, ETH Zurich / Statistik Stadt Zürich)

### March 21, 2018

- [Long Term Protection Model](slides/20180321_LTPM-in-R.pdf) (Alexis Iglauer, Partner Re, and Maarten-Jan Kallen, BeDataDriven, on behalf of Dr. Urszula Gasser, Partner Re)

- Social contact network analysis: static versus dynamic (time-stamped) approaches (Beatriz Vidondo, Veterinary Public Health Institute, Department of Clinical Research and Public Health, University of Bern)

### January 8, 2018

- [Big Data Analytics in R using sparklyr](https://www.slideshare.net/NicolaLambiase/big-data-analytics-in-r-using-sparklyr) (Nicola Lambiase, Mirai-Solutions)
    - also available as [Rmd](https://gist.github.com/lambiase/f07ba853618a9219137fee0764671c94#file-nyc_tlc-rmd) and [html](https://cdn.rawgit.com/lambiase/f07ba853618a9219137fee0764671c94/raw/4f65642e012704f087a93e337ee10b486d53e544/nyc_tlc.html) files

- [Anomaly detection – database integrated](https://www.slideshare.net/Zurich_R_User_Group/anomaly-detection-database-integrated) (Olaf Nimz, Trivadis)

### November 7, 2017

- [Read and process unstructured data with R](https://github.com/statistikZH/RMeetup/blob/master/unstructered_data.pdf) (Max Grütter, Statistical Office, Canton of Zurich)

- [Mastering Corporate Design with R](https://schnllr.github.io/Meetup) (Andrea Schnell and Thomas Lo Russo, Statistical Office, Canton of Zurich)

- [Illustration of pupils’ diversity with R](http://prezi.com/ao48t6yeh_vz/?utm_campaign=share&utm_medium=copy&rc=ex0share) (Flavian Imlig, Zurich State Department of Education)

- [Making Public Data Public](http://www.christophsax.com/slides/171107-meetup/slides.html) (Christoph Sax, Christoph Sax Data Analytics)

See also the [list of presentations](https://statistikzh.github.io/RMeetup/) provided by the [Statistical Office of the Canton of Zurich](http://statistik.zh.ch/).

### September 4, 2017

- [Open machine learning](https://openml.github.io/articles/slides/talk_cenisbs_2017/OpenML_CENISBS.html) (Heidi Seibold, Epidemiology, Biostatistics and Prevention Institute, UZH)

- [Dynamic Pricing - Analyzing rapidly-changing prices](https://docs.datahouse.ch/2017/RMeetup_September) (Daniel Meister, datahouse)

- [R at Sanitas – Workflow, Problems and
Solutions](https://www.slideshare.net/Zurich_R_User_Group/r-at-sanitas-workflow-problems-and-solutions) (Patrik Lengacher, Sanitas)

### May 3, 2017

- [Visualizing the frequency of delays using QGIS and the Leaflet javascript library in R](https://www.slideshare.net/Zurich_R_User_Group/visualizing-the-frequency-of-transit-delays-using-qgis-and-the-leaflet-javascript-library-in-r) (Peter B. Pearman and Thomas Roth)

- [Modelling Bus Bunching](https://www.slideshare.net/Zurich_R_User_Group/modeling-bus-bunching) (Andrea Farnham)

- How we organized the Hackathon (Heidi Seibold)

### April 10, 2017

- [Slides](https://github.com/krlmlr/remake-slides) and [tutorial](https://github.com/krlmlr/remake-tutorial) (Kirill Müller, ETHZ/datatools GmbH)

### February 6, 2017
- [Introduction to Renjin, the alternative engine for R ](https://www.slideshare.net/Zurich_R_User_Group/introduction-to-renjin-the-alternative-engine-for-r) (Maarten-Jan Kallen, BeDataDriven)

- [R, y u do dis? ](https://github.com/christophM/r-y-u-do-dis/blob/master/presentation.Rmd) (Christoph Molnar)

- Scraping Interactive Graphs with Selenium (Kushtrim Veseli, Swiss International Air Lines) ([Code](https://github.com/Zurich-R-User-Group/Zurich-R-User-Group.github.io/blob/master/_files/slides-code/538_polls_all.R))


### November 29, 2016 (How R is used in different professions)

- Make it simpleR! (Raymond Zychowicz, UBS)  

- [R in Finance: Using R in a productive and highly regulated environment](http://www.slideshare.net/Zurich_R_User_Group/rinfinancegabrielfoix) (Gabriel Foix, Mirai Solutions) 

- [R for Car Insurance Product](http://www.slideshare.net/Zurich_R_User_Group/how-to-use-r-in-different-professions-r-for-car-insurance-product-speaker-claudio-giancaterino) (Claudio Giancaterino) 

- Using Shiny for worldwide climate monitoring (David Masson, CelsiusPro)

### September 29, 2016

- [Fast Prototyping in R - a brief Introduction to R Shiny](http://htmlpreview.github.io/?https://github.com/Zurich-R-User-Group/Zurich-R-User-Group.github.io/blob/master/_files/slides/nadja-shiny/MeetupPresentation.html#/) (Nadja Ulrich, Zühlke) [Code](https://github.com/naulrich/ZurichRUserMeetup)

- [Clean, code, analyze and visualize election data in R: An example from datajournalism](http://www.slideshare.net/Zurich_R_User_Group/where-south-america-is-swinging-to-the-right-an-rdriven-data-journalism-project-from-neue-zrcher-zeitung) (Marie-José Kolly & Marvin Milatz, NZZ)


### August 4, 2016 (Visualisation special)

- [Analyzing the Bührer family data set using an advanced mosaic plot.](http://de.slideshare.net/Zurich_R_User_Group/analyzing-the-bhrer-family-data-set-using-an-advanced-mosaic-plot) (Thomas Roth, ZHAW)

- [Mapping health during travel: a visualization of a trip through Thailand.](http://de.slideshare.net/Zurich_R_User_Group/visualization-challenge-mapping-health-during-travel) (Andrea Farnham, UZH)

- [Interactive Javascript in R with rCharts](http://htmlpreview.github.io/?https://raw.githubusercontent.com/Zurich-R-User-Group/Zurich-R-User-Group.github.io/master/_files/slides/matteo-rcharts/index.html) (Matteo Casserini, Centralway)

- [Animation of political shifts in elections](https://github.com/srfdata/2015-09-elections-political-shifts/blob/master/analysis/main.Rmd) (Timo Grossenbacher, SRF)

- [An interactive map with R-Shiny and leaflet](http://de.slideshare.net/Zurich_R_User_Group/an-interactive-map-with-rshiny-and-leaflet) (Bojan Škerlak, Migros)

- [Federal election 2015 : visualizing the panachage-statistics](http://www.web.statistik.zh.ch/cms_vis/meetup/panachage.html) (Thomas Lo Russo, Statistical Office Zurich)

- [Crosstalk](https://raw.githubusercontent.com/dimitris1ps/zurichRMeetup/master/meetup.rmd) (Dimitris Psaradellis, eBay)


### May 23, 2016

- [Microsoft R Server](http://chilp.it/e690a33) (Marc Schöni, Microsoft)

- [Automated reports at OrganizationView](http://www.slideshare.net/AndrewMarritt/zurich-r-user-group-presentation-may-2016) (Andrew Marritt, OrganizationView)

### March 16, 2016

- [Data journalism](http://grssnbchr.github.io/zrug-rddj) (Timo Grossenbacher, SRF)

- [Open Data Zurich](http://de.slideshare.net/Opendatazurich/open-data-lt3-r) (Marco Sieber and Fidel Thomet, Open Data Zurich)

### January 21, 2016

- [Speeding up (big) data manipulation with the data.table package](http://de.slideshare.net/Zurich_R_User_Group/speeding-up-big-data-manipulation-with-datatable-package) (Vasily Tolkachev, Zurich University of Applied Sciences, Institute for Data Analysis and Process Design)

- [DescTools - Tools for Descriptive Statistics and Exploratory Data Analysis](http://de.slideshare.net/Zurich_R_User_Group/zurich-r-user-group-desc-tools) (Andri Signorell, Helsana/HWZ)  

### December 7, 2015

- [Shiny: Make Your R Code Interactive](http://de.slideshare.net/Zurich_R_User_Group/december-2015-meetup-shiny-make-your-r-code-interactive-craig-wang) (Craig Wang, ETH)

- Exploring knitr (Isaac Gravestock, UZH)

- [Improving computational performance with algorithm engineering](https://krlmlr-user15.github.io/presentation/#1) (Kirill Müller, ETH)
